/**
 * Supabase client + environment wiring.
 *
 * All values are read from Vite env vars (VITE_*). Copy `.env.example` to
 * `.env.local` and fill them in.
 *
 * Historically this file was autogenerated and committed with hardcoded
 * credentials. Those have been moved out and should be rotated; see
 * README.md → Phase 0 migration notes.
 */
import { createClient, type SupabaseClient } from '@supabase/supabase-js';

const rawUrl = import.meta.env.VITE_SUPABASE_URL;
const rawAnon = import.meta.env.VITE_SUPABASE_ANON_KEY;
const functionSlug = import.meta.env.VITE_SUPABASE_FUNCTION_SLUG ?? 'make-server-56c079d7';

if (!rawUrl || !rawAnon) {
  // Fail loudly in dev, but don't hard-crash prod — we log and let the UI
  // surface a friendlier error. Build-time this is typically statically
  // replaced, so missing values surface at `npm run build`.
  const msg =
    'Missing VITE_SUPABASE_URL or VITE_SUPABASE_ANON_KEY. Copy .env.example to .env.local and fill in real values.';
  if (import.meta.env.DEV) {
    throw new Error(msg);
  }
  // eslint-disable-next-line no-console
  console.error(msg);
}

export const supabaseUrl: string = rawUrl ?? '';
export const supabaseAnonKey: string = rawAnon ?? '';
export const apiBase: string = `${supabaseUrl}/functions/v1/${functionSlug}`;

/** Shared Supabase client — handles auth session + refresh tokens. */
export const supabase: SupabaseClient = createClient(supabaseUrl, supabaseAnonKey, {
  auth: {
    persistSession: true,
    autoRefreshToken: true,
    detectSessionInUrl: true,
  },
});

/**
 * Authenticated fetch to the edge function. Automatically attaches the
 * current user's JWT as `Authorization: Bearer <access_token>` so the server
 * can verify identity — never trust client-supplied user IDs.
 */
export async function authedFetch(path: string, init: RequestInit = {}): Promise<Response> {
  const { data } = await supabase.auth.getSession();
  const token = data.session?.access_token ?? supabaseAnonKey;

  const headers = new Headers(init.headers ?? {});
  headers.set('Authorization', `Bearer ${token}`);
  if (init.body && !headers.has('Content-Type')) {
    headers.set('Content-Type', 'application/json');
  }

  return fetch(`${apiBase}${path.startsWith('/') ? path : `/${path}`}`, {
    ...init,
    headers,
  });
}

// ----------------------------------------------------------------------------
// Legacy compatibility exports — DEPRECATED. Kept so existing components keep
// compiling during the auth migration. Remove once all callers use
// `authedFetch` or the supabase client directly.
// ----------------------------------------------------------------------------

/** @deprecated use `supabaseUrl` or `apiBase`. */
export const projectId: string = supabaseUrl
  .replace(/^https?:\/\//, '')
  .replace(/\.supabase\.co\/?$/, '');

/** @deprecated use `supabaseAnonKey`. */
export const publicAnonKey: string = supabaseAnonKey;
